export type { ConicParams } from "./conics";
export {
  circleTangentLines,
  circleTangentsFromPoint,
  conicFeatureLineFromParams,
  conicFeatureLineShape,
  conicFeaturePointFromParams,
  conicFeaturePointPosition,
  conicParamsAt,
  conicPointPosition,
  conicTangentFromParams,
  invertConicParam,
  parabolaThroughPoints,
  resolveConic,
  sampleConic,
  sampleThreePointParabola,
  tangentToConicAt,
} from "./conics";
export { enforceLocks } from "./constraints";
export type {
  AngleBisector,
  Animation,
  AnimationMode,
  AnimationVariant,
  AxisFrame,
  AxisSystem,
  Calculation,
  Circle,
  CircleCenterPoint,
  Circumcircle,
  Conic,
  ConicFeatureName,
  ConicLine,
  DocumentMarks,
  FreePoint,
  FunctionPlot,
  GeoDocument,
  GeoObject,
  IntersectionPoint,
  Iteration,
  Line,
  Locus,
  Measurement,
  MeasureQuantity,
  Midpoint,
  NumberAxis,
  ObjectId,
  ObjectStyle,
  OnCirclePoint,
  OnConicPoint,
  OnFunctionPoint,
  OnLinearPoint,
  OnLocusPoint,
  OnParametricPoint,
  OnPolygonPoint,
  ParallelLine,
  ParametricCurve,
  PerpendicularLine,
  PointObject,
  Polygon,
  Presentable,
  Ray,
  Segment,
  TangentLine,
  ThreePointParabola,
  TransformedPoint,
  TransformedShape,
  TransformSpec,
  TriangleCenterKind,
  TriangleCenterPoint,
  Variable,
} from "./document";
export {
  addObject,
  addObjects,
  angleBisector,
  angleMeasure,
  areaOf,
  axisFrame,
  axisSystemOf,
  calculationAt,
  circle,
  circleCenterOf,
  circumcenterOf,
  circumcircleOf,
  conicFeaturePointOf,
  conicLineOf,
  conicOf,
  coordinateFrameFor,
  coordinatesInFrame,
  createDocument,
  createId,
  curveAxisIntersectionNear,
  dependenciesOf,
  distanceBetween,
  driverAnimationOf,
  externalBisector,
  freePoint,
  functionPlotOf,
  groupAnimationOf,
  intersectGraphWithLinear,
  intersectionOf,
  invertLocus,
  isGeoObject,
  iterationOf,
  iterationPoints,
  lengthOf,
  line,
  listObjects,
  locusOf,
  locusPoints,
  midpointOf,
  movePoint,
  moveTextPosition,
  numberAxisOf,
  parallelLine,
  parametricCurveOf,
  parametricIntersectionNear,
  parametricPointEvaluator,
  parseDocument,
  perpendicularLine,
  plotRangeContains,
  pointOnCircle,
  pointOnConic,
  pointOnFunction,
  pointOnLinear,
  pointOnLocus,
  pointOnParametric,
  pointOnPolygon,
  pointPosition,
  polygon,
  polygonVerticesOf,
  ray,
  remapObjectReferences,
  removeObject,
  renameObject,
  resolvePositions,
  resolveShapePositions,
  resolveTransformedPolygon,
  segment,
  serializeDocument,
  setCalculationExpression,
  setMark,
  setObjectHidden,
  setObjectTraced,
  setPointLocked,
  setValueLock,
  setVariableRange,
  setVariableValue,
  slidePoint,
  tangentLineOf,
  threePointParabolaOf,
  toggleAnimationOf,
  transformedPoint,
  transformedShape,
  triangleCenterOf,
  updateAnimationSettings,
  updateObjectStyle,
  updatePlotExpressions,
  updatePointDisplay,
  variableAnimationOf,
  variableAt,
} from "./document";
export { evaluateExpression } from "./expression";
export {
  ensureComputeEngine,
  evaluateLatex,
  isLatexValid,
  latexToExpression,
  variableScope,
} from "./functionEval";
export type { ResolvedShape, XY } from "./geometry";
export {
  bisectorDirection,
  derivedLineThrough,
  distance,
  distancePointToLine,
  distancePointToRay,
  distancePointToSegment,
  distanceToShape,
  intersectCircles,
  intersectShapes,
  midpoint,
  minimizeScalar,
  nearestAngleStep,
  pointInPolygon,
  projectOntoDirectedLine,
} from "./geometry";
export type { ViewBox } from "./plots";
export {
  distanceToFragments,
  graphIntersectionNear,
  graphValueAt,
  invertParametric,
  sampleFunction,
  sampleParametric,
} from "./plots";
export { findGraphRootNear, findRootsInDomain } from "./rootFinding";
export {
  computeValue,
  evaluateCalculationExpression,
  formatValue,
  isValueObject,
  listValueObjects,
  objectNameError,
  valueIndexOf,
} from "./values";
